/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "spi.h"
#include "systick.h"
#include "uart.h"
#include "NRF24L01.h"
#include "stm32f446xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ce_low() (GPIOA->BSRR=(1<<24))
#define ce_high() (GPIOA->BSRR=(1<<8))

char status;
uint8_t msg[32];
uint8_t msg2[32]="HELLO\r\n";

volatile uint8_t idx = 0;

void USART2_Print(char *msg)
{
    while(*msg)
    {
        uart2_write(*msg++);
    }
}


int main(void)
{
	spi1_gpio_init();
	spi1_config();
	systickDelayMs_polling(100);
	NRF_init_transmit();
	uart2_rxtx_init();




	while(1){

		//NRF_Transmit(msg2, 32);



	}
}



void USART2_IRQHandler(void)
{
    if(USART2->SR & (1<<5))
    {
        msg[idx++] = USART2->DR;


        if(msg[idx-1] == ';')
        {
            idx = 0;
			NRF_Transmit(msg, 32);
        }
    }

}
